In [1]:
# import packages
import numpy as np
import pandas as pd
from collections import defaultdict
from scipy.sparse import csc_matrix
np.random.seed(seed=2019)

In [5]:
sig_matrix = np.array([[3, 0, 3],
       [3, 0, 3],
       [3, 0, 5]])

In [6]:
sig_matrix

array([[3, 0, 3],
       [3, 0, 3],
       [3, 0, 5]])

In [8]:
df = pd.DataFrame(sig_matrix)

a = df.apply(lambda x: hash(tuple(x)), axis = 1)

In [16]:
type(a)
for index, x in np.ndenumerate(a):
    print(index[0],x)

0 5050907061199316999
1 5050907061199316999
2 5050907061196986901


In [127]:
bands = 3
rows = 1
def LSH_bucket(sig_matrix):
    bucket_list = defaultdict(set)
    if bands * rows != sig_matrix.shape[0]:
        print('#bands * #rows is not equal to #signatures')
    else:
        for b in range(bands):
            s = np.sum(sig_matrix[b*rows:(b+1)*rows,:], axis =0)
            for index, x in np.ndenumerate(s):
                bucket_list[x].add(index[0])
        return bucket_list.items()

In [131]:
def calculate_jsim(a,b):
    intersect = set(a) & set(b)
    union = set(a) | set(b)
    jsim = len(intersect)/len(union)
    return jsim

In [128]:
bucket_list = LSH_bucket(sig_matrix)

In [129]:
bucket_list

dict_items([(3, {0, 2}), (0, {1})])

In [150]:
unique_pairs = set()
sim_pairs = set()
for key, value in bucket_list:
    if len(value) > 1 :#and len(value) < 100: # remove the duplicate pairs
        for i in value:
            for j in value:
                if i < j and ((i,j) not in unique_pairs):
                    unique_pairs.add((i,j))
                    sigi = sig_matrix[:,i].ravel().tolist()
                    sigj = sig_matrix[:,j].ravel().tolist()
                    jsim = calculate_jsim(sigi, sigj)
                    if jsim > 0.5:
                        sim_pairs.add((i,j))

In [64]:
sum(np.array([ True, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True, False, False, False,
       False, False, False,  True, False, False, False,  True,  True,
       False,  True,  True, False, False, False,  True, False, False,
       False, False,  True, False, False,  True, False, False, False,
       False,  True,  True,  True,  True, False, False, False, False,
       False, False,  True, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False, False,
        True,  True,  True, False, False, False, False,  True, False,
        True, False,  True,  True, False, False,  True,  True,  True,
        True,  True,  True, False, False,  True, False, False,  True,
        True]))

50

In [141]:
for key, value in bucket_list:
    print(key,value,len(value))
    for i in value:
        print(i)

3 {0, 2} 2
0
2
0 {1} 1
1


In [143]:
sigi = sig_matrix[:,1].ravel().tolist()[0]

In [158]:
sig_matrix[:,1].tolist()

[0, 0, 0]

In [148]:
sig_matrix

array([[3, 0, 3],
       [3, 0, 3],
       [3, 0, 3]])

In [154]:
true_pairs = []
for pair in sim_pairs:
    jsim = calculate_jsim(m_by_u[pair[0]], m_by_u[pair[1]])
    if jsim>0.4:
        true_pairs.append(pair)
true_pairs

[(0, 2)]

In [1]:
def fun(a):
    if a>5:
        return a

In [61]:
import numpy as np
b =np.array([[0,0,1],[1,1,0],[2,0,1],[3,0,1]]) 


In [62]:
b[[1,0,2,3]]

array([[1, 1, 0],
       [0, 0, 1],
       [2, 0, 1],
       [3, 0, 1]])

In [59]:
for i in range(10):
    row_sel = np.random.permutation(data.shape[0])
    data_perm = data[row_sel,:]
    for j in range(data.shape[1]):
        loc = data_perm.indices[data_perm.indptr[j]:data_perm.indptr[j+1]].min()
        sig_mat[i,j] = loc

NameError: name 'data' is not defined

In [39]:
b = (b==1)
b

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [False, False,  True]])

In [38]:
import csv
a = {(91164, 94943),
 (54673, 80723),
 (44104, 52055),
 (31587, 54742),
 (27208, 95649),
 (48153, 49656),
 (37197, 95887),
 (51463, 58534)}
for pair in a:
    with open('ans.txt','a') as file:
        writer = csv.DictWriter(file,fieldnames=['user1', 'user2'])
        writer.writerow({'user1':pair[0],'user2':pair[1]})

In [65]:
a = np.array([ 8., 15., 50.,  8., 17.,  5., 16.,  4.,  4.,  2., 17., 16.,  1.,
        8.,  7.,  9.,  9., 32., 49., 16., 18.,  8.,  2., 27.,  8.,  3.,
        4.,  6.,  1., 15.,  5.,  7.,  7.,  3., 13.,  7.,  3., 12., 41.,
       23.,  1.,  0.,  1.,  6., 12., 16., 11.,  6.,  9.,  5., 10.,  6.,
        6.,  2.,  1.,  1.,  5.,  2.,  2., 10.,  9.,  9.,  8., 15., 25.,
       10.,  3., 21., 11., 18.,  8., 31., 10.,  3.,  9., 10.,  7., 19.,
        0.,  3., 18., 27., 12.,  6., 11.,  7.,  5.,  3.,  3.,  5., 11.,
       14., 18., 11.,  4., 18., 23.,  1.,  9.,  1.])
b = np.array([ 8., 12., 24., 11.,  6.,  5., 16.,  4.,  4.,  2., 17., 16.,  9.,
        8.,  7., 16., 10., 34.,  7., 18.,  5.,  8.,  4.,  1.,  5.,  3.,
        4., 11.,  1., 15., 12., 11., 11.,  3., 25.,  1.,  8., 16., 41.,
       25., 13.,  0., 11., 28., 30., 19., 11.,  6.,  9.,  5.,  3.,  1.,
       20.,  9.,  7., 17.,  5., 18.,  2., 10.,  9.,  9.,  8., 11., 25.,
       10.,  3., 21., 11., 18., 60., 44., 10.,  3.,  9., 14., 23., 21.,
       12.,  3.,  7., 27., 13.,  6., 11., 31., 26.,  3.,  3.,  5., 11.,
       14., 18.,  2.,  8., 18.,  3.,  6.,  9.,  1.])

In [79]:
%timeit np.count_nonzero(a==b)

923 ns ± 44 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [80]:
%timeit sum(a==b)

229 µs ± 9.39 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [83]:
t0 = time.time()

for i in range(100000):
    np.count_nonzero(a==b)
print("Running time:", time.time()-t0, "s" )

Running time: 0.10797810554504395 s


In [84]:
t0 = time.time()

for i in range(100000):
    sum(a==b)
print("Running time:", time.time()-t0, "s" )

Running time: 24.00898790359497 s


In [85]:
np.count_nonzero(a==b)

50

In [86]:
25/100

0.25

In [111]:
a = np.array([[1,2,3],[1,2,3]])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [114]:
np.prod(a ,axis = 1)

array([6, 6])

In [93]:
np.array(map(str, a))

array(<map object at 0x10a6cc240>, dtype=object)

In [99]:
print(b)

In [102]:
def myfunc(n):
    return len(n)

list(map(myfunc, ('apple', 'banana', 'cherry')))

[5, 6, 6]